In [4]:
import pandas as pd

In [5]:
ruta = "C:\\Users\\WIN10\\Desktop\\DS_TOTAL\\FE Guide_1.csv"

In [31]:
FE = pd.read_csv(ruta, sep = ";")
FE.head(5)

,Model Year,Mfr Name,Division,Carline,Verify Mfr Cd,Index (Model Type Index),Eng Displ,# Cyl,Transmission,City FE (Guide) - Conventional Fuel,...,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe
0,2021,Honda,Acura,NSX,HNX,39,"3,5",6,Auto(AM-S9),21,...,4000.0,420,406,420,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,aston martin,Aston Martin Lagonda Ltd,Vantage Manual,ASX,5,4,8,Manual(M7),14,...,6750.0,636,426,541,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,aston martin,Aston Martin Lagonda Ltd,Vantage V8,ASX,4,4,8,Auto(S8),18,...,4750.0,494,364,435,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,Volkswagen Group of,Audi,R8,VGA,5,"5,2",10,Auto(AM-S7),13,...,7750.0,663,450,567,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,Volkswagen Group of,Audi,R8 2WD,VGA,7,"5,2",10,Auto(AM-S7),14,...,6750.0,645,386,528,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
NSX = FE.copy()
pd.isnull(NSX)

,Model Year,Mfr Name,Division,Carline,Verify Mfr Cd,Index (Model Type Index),Eng Displ,# Cyl,Transmission,City FE (Guide) - Conventional Fuel,...,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
1161,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
1162,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
1163,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
1164,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True

In [12]:
NSX = FE.copy()
pd.notnull(NSX)

,Model Year,Mfr Name,Division,Carline,Verify Mfr Cd,Index (Model Type Index),Eng Displ,# Cyl,Transmission,City FE (Guide) - Conventional Fuel,...,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,False,False,False,False,False
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,False,False,False,False,False
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,False,False,False,False,False
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,False,False,False,False,False
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,False,False,False,False,False
1161,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,False,False,False,False,False
1162,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,False,False,False,False,False
1163,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,False,False,False,False,False
1164,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,False,False,False,False,False

In [13]:
NSX = FE.copy()
pd.isnull(NSX).values.sum()

98582

In [14]:
NSX = FE.copy()
pd.notnull(NSX).values.sum()

81993

In [15]:
NSX = FE.copy()
NSX = NSX.fillna("LIMPIEZA DE DATOS")
NSX

,Model Year,Mfr Name,Division,Carline,Verify Mfr Cd,Index (Model Type Index),Eng Displ,# Cyl,Transmission,City FE (Guide) - Conventional Fuel,...,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe
0,2021,Honda,Acura,NSX,HNX,39,"3,5",6,Auto(AM-S9),21,...,4000.0,420,406,420,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS
1,2021,aston martin,Aston Martin Lagonda Ltd,Vantage Manual,ASX,5,4,8,Manual(M7),14,...,6750.0,636,426,541,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS
2,2021,aston martin,Aston Martin Lagonda Ltd,Vantage V8,ASX,4,4,8,Auto(S8),18,...,4750.0,494,364,435,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS
3,2021,Volkswagen Group of,Audi,R8,VGA,5,"5,2",10,Auto(AM-S7),13,...,7750.0,663,450,567,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS
4,2021,Volkswagen Group of,Audi,R8 2WD,VGA,7,"5,2",10,Auto(AM-S7),14,...,6750.0,645,386,528,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,2021,Toyota,TOYOTA,LAND CRUISER WAGON 4WD,TYX,6,"5,7",8,Auto(S8),13,...,7000.0,698,520,618,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS
1161,2021,Toyota,TOYOTA,SEQUOIA 4WD,TYX,34,"5,7",8,Auto(S6),13,...,7000.0,697,521,618,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS
1162,2021,Volkswagen Group of,Volkswagen,Atlas 4Motion,VGA,1,"3,6",6,Auto(S8),16,...,3750.0,547,409,485,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS
1163,2021,Volvo,"Volvo Cars of North America, LLC",XC90 AWD,VVX,52,2,4,Auto(S8),19,...,3500.0,456,318,394,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS
1164,2021,Volvo,"Volvo Cars of North America, LLC",XC90 AWD,VVX,53,2,4,Auto(S8),20,...,3000.0,433,314,380,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS,LIMPIEZA DE DATOS

In [24]:
NSX = FE.copy()
NSX["CO2-PHEV Composit"] = NSX["CO2-PHEV Composit"].fillna("-")

NSX["240V Charge Ti"] = NSX["240V Charge Ti"].fillna("sin datos")

NSX["120V Charge time at 120 Volts (hours)"] = NSX["120V Charge time at 120 Volts (hours)"].fillna("LIMPIEZA")

NSX["City PHEV Composite MPGe"] = NSX["City PHEV Composite MPGe"].fillna("TABAJANDO")

NSX["Comb PHEV Composite MPGe"] = NSX["Comb PHEV Composite MPGe"].fillna("SIN INFORMACION")

NSX["Hwy PHEV Composite MPGe"] = NSX["Hwy PHEV Composite MPGe"].fillna("INVESTIGANDO")

NSX.head(5)

,Model Year,Mfr Name,Division,Carline,Verify Mfr Cd,Index (Model Type Index),Eng Displ,# Cyl,Transmission,City FE (Guide) - Conventional Fuel,...,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe
0,2021,Honda,Acura,NSX,HNX,39,"3,5",6,Auto(AM-S9),21,...,4000.0,420,406,420,-,sin datos,LIMPIEZA,TABAJANDO,INVESTIGANDO,SIN INFORMACION
1,2021,aston martin,Aston Martin Lagonda Ltd,Vantage Manual,ASX,5,4,8,Manual(M7),14,...,6750.0,636,426,541,-,sin datos,LIMPIEZA,TABAJANDO,INVESTIGANDO,SIN INFORMACION
2,2021,aston martin,Aston Martin Lagonda Ltd,Vantage V8,ASX,4,4,8,Auto(S8),18,...,4750.0,494,364,435,-,sin datos,LIMPIEZA,TABAJANDO,INVESTIGANDO,SIN INFORMACION
3,2021,Volkswagen Group of,Audi,R8,VGA,5,"5,2",10,Auto(AM-S7),13,...,7750.0,663,450,567,-,sin datos,LIMPIEZA,TABAJANDO,INVESTIGANDO,SIN INFORMACION
4,2021,Volkswagen Group of,Audi,R8 2WD,VGA,7,"5,2",10,Auto(AM-S7),14,...,6750.0,645,386,528,-,sin datos,LIMPIEZA,TABAJANDO,INVESTIGANDO,SIN INFORMACION

In [26]:
NSX.head(5)

,Model Year,Mfr Name,Division,Carline,Verify Mfr Cd,Index (Model Type Index),Eng Displ,# Cyl,Transmission,City FE (Guide) - Conventional Fuel,...,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe
0,2021,Honda,Acura,NSX,HNX,39,"3,5",6,Auto(AM-S9),21,...,4000.0,420,406,420,-,sin datos,LIMPIEZA,TABAJANDO,INVESTIGANDO,SIN INFORMACION
1,2021,aston martin,Aston Martin Lagonda Ltd,Vantage Manual,ASX,5,4,8,Manual(M7),14,...,6750.0,636,426,541,-,sin datos,LIMPIEZA,TABAJANDO,INVESTIGANDO,SIN INFORMACION
2,2021,aston martin,Aston Martin Lagonda Ltd,Vantage V8,ASX,4,4,8,Auto(S8),18,...,4750.0,494,364,435,-,sin datos,LIMPIEZA,TABAJANDO,INVESTIGANDO,SIN INFORMACION
3,2021,Volkswagen Group of,Audi,R8,VGA,5,"5,2",10,Auto(AM-S7),13,...,7750.0,663,450,567,-,sin datos,LIMPIEZA,TABAJANDO,INVESTIGANDO,SIN INFORMACION
4,2021,Volkswagen Group of,Audi,R8 2WD,VGA,7,"5,2",10,Auto(AM-S7),14,...,6750.0,645,386,528,-,sin datos,LIMPIEZA,TABAJANDO,INVESTIGANDO,SIN INFORMACION

In [28]:
pd.isnull(NSX).values.sum()

91592

In [29]:
pd.notnull(NSX).values.sum()

88983

In [34]:
FE.head(3)

,Model Year,Mfr Name,Division,Carline,Verify Mfr Cd,Index (Model Type Index),Eng Displ,# Cyl,Transmission,City FE (Guide) - Conventional Fuel,...,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe
0,2021,Honda,Acura,NSX,HNX,39,"3,5",6,Auto(AM-S9),21,...,4000.0,420,406,420,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,aston martin,Aston Martin Lagonda Ltd,Vantage Manual,ASX,5,4,8,Manual(M7),14,...,6750.0,636,426,541,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,aston martin,Aston Martin Lagonda Ltd,Vantage V8,ASX,4,4,8,Auto(S8),18,...,4750.0,494,364,435,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
NSX = FE.copy()
NSX["CO2-PHEV Composit"] = NSX["CO2-PHEV Composit"].fillna(" - ")
NSX

,Model Year,Mfr Name,Division,Carline,Verify Mfr Cd,Index (Model Type Index),Eng Displ,# Cyl,Transmission,City FE (Guide) - Conventional Fuel,...,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe
0,2021,Honda,Acura,NSX,HNX,39,"3,5",6,Auto(AM-S9),21,...,4000.0,420,406,420,-,NaN,NaN,NaN,NaN,NaN
1,2021,aston martin,Aston Martin Lagonda Ltd,Vantage Manual,ASX,5,4,8,Manual(M7),14,...,6750.0,636,426,541,-,NaN,NaN,NaN,NaN,NaN
2,2021,aston martin,Aston Martin Lagonda Ltd,Vantage V8,ASX,4,4,8,Auto(S8),18,...,4750.0,494,364,435,-,NaN,NaN,NaN,NaN,NaN
3,2021,Volkswagen Group of,Audi,R8,VGA,5,"5,2",10,Auto(AM-S7),13,...,7750.0,663,450,567,-,NaN,NaN,NaN,NaN,NaN
4,2021,Volkswagen Group of,Audi,R8 2WD,VGA,7,"5,2",10,Auto(AM-S7),14,...,6750.0,645,386,528,-,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,2021,Toyota,TOYOTA,LAND CRUISER WAGON 4WD,TYX,6,"5,7",8,Auto(S8),13,...,7000.0,698,520,618,-,NaN,NaN,NaN,NaN,NaN
1161,2021,Toyota,TOYOTA,SEQUOIA 4WD,TYX,34,"5,7",8,Auto(S6),13,...,7000.0,697,521,618,-,NaN,NaN,NaN,NaN,NaN
1162,2021,Volkswagen Group of,Volkswagen,Atlas 4Motion,VGA,1,"3,6",6,Auto(S8),16,...,3750.0,547,409,485,-,NaN,NaN,NaN,NaN,NaN
1163,2021,Volvo,"Volvo Cars of North America, LLC",XC90 AWD,VVX,52,2,4,Auto(S8),19,...,3500.0,456,318,394,-,NaN,NaN,NaN,NaN,NaN
1164,2021,Volvo,"Volvo Cars of North America, LLC",XC90 AWD,VVX,53,2,4,Auto(S8),20,...,3000.0,433,314,380,-,NaN,NaN,NaN,NaN,NaN

In [40]:
NSX = FE.copy()
NSX[["CO2-PHEV Composit","240V Charge Ti","120V Charge time at 120 Volts (hours)"]] = NSX[
    ["CO2-PHEV Composit","240V Charge Ti","120V Charge time at 120 Volts (hours)"]].fillna("-")

NSX

,Model Year,Mfr Name,Division,Carline,Verify Mfr Cd,Index (Model Type Index),Eng Displ,# Cyl,Transmission,City FE (Guide) - Conventional Fuel,...,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe
0,2021,Honda,Acura,NSX,HNX,39,"3,5",6,Auto(AM-S9),21,...,4000.0,420,406,420,-,-,-,NaN,NaN,NaN
1,2021,aston martin,Aston Martin Lagonda Ltd,Vantage Manual,ASX,5,4,8,Manual(M7),14,...,6750.0,636,426,541,-,-,-,NaN,NaN,NaN
2,2021,aston martin,Aston Martin Lagonda Ltd,Vantage V8,ASX,4,4,8,Auto(S8),18,...,4750.0,494,364,435,-,-,-,NaN,NaN,NaN
3,2021,Volkswagen Group of,Audi,R8,VGA,5,"5,2",10,Auto(AM-S7),13,...,7750.0,663,450,567,-,-,-,NaN,NaN,NaN
4,2021,Volkswagen Group of,Audi,R8 2WD,VGA,7,"5,2",10,Auto(AM-S7),14,...,6750.0,645,386,528,-,-,-,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,2021,Toyota,TOYOTA,LAND CRUISER WAGON 4WD,TYX,6,"5,7",8,Auto(S8),13,...,7000.0,698,520,618,-,-,-,NaN,NaN,NaN
1161,2021,Toyota,TOYOTA,SEQUOIA 4WD,TYX,34,"5,7",8,Auto(S6),13,...,7000.0,697,521,618,-,-,-,NaN,NaN,NaN
1162,2021,Volkswagen Group of,Volkswagen,Atlas 4Motion,VGA,1,"3,6",6,Auto(S8),16,...,3750.0,547,409,485,-,-,-,NaN,NaN,NaN
1163,2021,Volvo,"Volvo Cars of North America, LLC",XC90 AWD,VVX,52,2,4,Auto(S8),19,...,3500.0,456,318,394,-,-,-,NaN,NaN,NaN
1164,2021,Volvo,"Volvo Cars of North America, LLC",XC90 AWD,VVX,53,2,4,Auto(S8),20,...,3000.0,433,314,380,-,-,-,NaN,NaN,NaN

In [44]:
NSX = FE.copy()
NSX[["CO2-PHEV Composit","240V Charge Ti","120V Charge time at 120 Volts (hours)"]] = NSX[
    ["CO2-PHEV Composit","240V Charge Ti","120V Charge time at 120 Volts (hours)"]].fillna("-")

NSX["Comb PHEV Composite MPGe"] = NSX["Comb PHEV Composite MPGe"].fillna(1000)
NSX["Hwy PHEV Composite MPGe"] = NSX["Hwy PHEV Composite MPGe"].fillna(2000)
NSX["City PHEV Composite MPGe"] = NSX["City PHEV Composite MPGe"].fillna(3000)

NSX.head(5)

,Model Year,Mfr Name,Division,Carline,Verify Mfr Cd,Index (Model Type Index),Eng Displ,# Cyl,Transmission,City FE (Guide) - Conventional Fuel,...,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe
0,2021,Honda,Acura,NSX,HNX,39,"3,5",6,Auto(AM-S9),21,...,4000.0,420,406,420,-,-,-,3000.0,2000.0,1000.0
1,2021,aston martin,Aston Martin Lagonda Ltd,Vantage Manual,ASX,5,4,8,Manual(M7),14,...,6750.0,636,426,541,-,-,-,3000.0,2000.0,1000.0
2,2021,aston martin,Aston Martin Lagonda Ltd,Vantage V8,ASX,4,4,8,Auto(S8),18,...,4750.0,494,364,435,-,-,-,3000.0,2000.0,1000.0
3,2021,Volkswagen Group of,Audi,R8,VGA,5,"5,2",10,Auto(AM-S7),13,...,7750.0,663,450,567,-,-,-,3000.0,2000.0,1000.0
4,2021,Volkswagen Group of,Audi,R8 2WD,VGA,7,"5,2",10,Auto(AM-S7),14,...,6750.0,645,386,528,-,-,-,3000.0,2000.0,1000.0

In [45]:
NSX = FE.copy()

In [47]:
NSX.head(5)

,Model Year,Mfr Name,Division,Carline,Verify Mfr Cd,Index (Model Type Index),Eng Displ,# Cyl,Transmission,City FE (Guide) - Conventional Fuel,...,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe
0,2021,Honda,Acura,NSX,HNX,39,"3,5",6,Auto(AM-S9),21,...,4000.0,420,406,420,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,aston martin,Aston Martin Lagonda Ltd,Vantage Manual,ASX,5,4,8,Manual(M7),14,...,6750.0,636,426,541,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,aston martin,Aston Martin Lagonda Ltd,Vantage V8,ASX,4,4,8,Auto(S8),18,...,4750.0,494,364,435,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,Volkswagen Group of,Audi,R8,VGA,5,"5,2",10,Auto(AM-S7),13,...,7750.0,663,450,567,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,Volkswagen Group of,Audi,R8 2WD,VGA,7,"5,2",10,Auto(AM-S7),14,...,6750.0,645,386,528,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
NSX = FE.copy()
NSX = NSX.dropna(axis = 1, how = "all")
NSX

,Model Year,Mfr Name,Division,Carline,Verify Mfr Cd,Index (Model Type Index),Eng Displ,# Cyl,Transmission,City FE (Guide) - Conventional Fuel,...,GHG Rating (1-10 rating on Label),GHG 1-10 rating on Ethanol (EPA Determined),#1 Smog Rating Test Group,#1 Mfr Smog Rating,#2 Smog Rating Test Group,#2 Mfr Smog Rating,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun
0,2021,Honda,Acura,NSX,HNX,39,"3,5",6,Auto(AM-S9),21,...,4,NaN,MHNXV03.5EBN,3,NaN,NaN,4000.0,420,406,420
1,2021,aston martin,Aston Martin Lagonda Ltd,Vantage Manual,ASX,5,4,8,Manual(M7),14,...,3,NaN,MASXV04.0AES,3,NaN,NaN,6750.0,636,426,541
2,2021,aston martin,Aston Martin Lagonda Ltd,Vantage V8,ASX,4,4,8,Auto(S8),18,...,4,NaN,MASXV04.0AES,3,NaN,NaN,4750.0,494,364,435
3,2021,Volkswagen Group of,Audi,R8,VGA,5,"5,2",10,Auto(AM-S7),13,...,2,NaN,MVGAV05.2NBE,1,NaN,NaN,7750.0,663,450,567
4,2021,Volkswagen Group of,Audi,R8 2WD,VGA,7,"5,2",10,Auto(AM-S7),14,...,3,NaN,MVGAV05.2NBE,1,NaN,NaN,6750.0,645,386,528
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,2021,Toyota,TOYOTA,LAND CRUISER WAGON 4WD,TYX,6,"5,7",8,Auto(S8),13,...,1,NaN,MTYXT05.7K6Y,3,NaN,NaN,7000.0,698,520,618
1161,2021,Toyota,TOYOTA,SEQUOIA 4WD,TYX,34,"5,7",8,Auto(S6),13,...,1,NaN,MTYXT05.7M5W,5,NaN,NaN,7000.0,697,521,618
1162,2021,Volkswagen Group of,Volkswagen,Atlas 4Motion,VGA,1,"3,6",6,Auto(S8),16,...,3,NaN,MVGAT03.6VAS,5,NaN,NaN,3750.0,547,409,485
1163,2021,Volvo,"Volvo Cars of North America, LLC",XC90 AWD,VVX,52,2,4,Auto(S8),19,...,4,NaN,MVVXJ02.0S30,7,NaN,NaN,3500.0,456,318,394
1164,2021,Volvo,"Volvo Cars of North America, LLC",XC90 AWD,VVX,53,2,4,Auto(S8),20,...,5,NaN,MVVXJ02.0U70,5,NaN,NaN,3000.0,433,314,380

In [52]:
NSX = FE.copy()
NSX

,Model Year,Mfr Name,Division,Carline,Verify Mfr Cd,Index (Model Type Index),Eng Displ,# Cyl,Transmission,City FE (Guide) - Conventional Fuel,...,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe
0,2021,Honda,Acura,NSX,HNX,39,"3,5",6,Auto(AM-S9),21,...,4000.0,420,406,420,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,aston martin,Aston Martin Lagonda Ltd,Vantage Manual,ASX,5,4,8,Manual(M7),14,...,6750.0,636,426,541,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,aston martin,Aston Martin Lagonda Ltd,Vantage V8,ASX,4,4,8,Auto(S8),18,...,4750.0,494,364,435,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,Volkswagen Group of,Audi,R8,VGA,5,"5,2",10,Auto(AM-S7),13,...,7750.0,663,450,567,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,Volkswagen Group of,Audi,R8 2WD,VGA,7,"5,2",10,Auto(AM-S7),14,...,6750.0,645,386,528,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,2021,Toyota,TOYOTA,LAND CRUISER WAGON 4WD,TYX,6,"5,7",8,Auto(S8),13,...,7000.0,698,520,618,NaN,NaN,NaN,NaN,NaN,NaN
1161,2021,Toyota,TOYOTA,SEQUOIA 4WD,TYX,34,"5,7",8,Auto(S6),13,...,7000.0,697,521,618,NaN,NaN,NaN,NaN,NaN,NaN
1162,2021,Volkswagen Group of,Volkswagen,Atlas 4Motion,VGA,1,"3,6",6,Auto(S8),16,...,3750.0,547,409,485,NaN,NaN,NaN,NaN,NaN,NaN
1163,2021,Volvo,"Volvo Cars of North America, LLC",XC90 AWD,VVX,52,2,4,Auto(S8),19,...,3500.0,456,318,394,NaN,NaN,NaN,NaN,NaN,NaN
1164,2021,Volvo,"Volvo Cars of North America, LLC",XC90 AWD,VVX,53,2,4,Auto(S8),20,...,3000.0,433,314,380,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
import pandas as pd

In [55]:
NSX = FE.copy()
NSX = NSX.dropna(axis = 0, how = "all")
NSX

,Model Year,Mfr Name,Division,Carline,Verify Mfr Cd,Index (Model Type Index),Eng Displ,# Cyl,Transmission,City FE (Guide) - Conventional Fuel,...,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe
0,2021,Honda,Acura,NSX,HNX,39,"3,5",6,Auto(AM-S9),21,...,4000.0,420,406,420,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,aston martin,Aston Martin Lagonda Ltd,Vantage Manual,ASX,5,4,8,Manual(M7),14,...,6750.0,636,426,541,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,aston martin,Aston Martin Lagonda Ltd,Vantage V8,ASX,4,4,8,Auto(S8),18,...,4750.0,494,364,435,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,Volkswagen Group of,Audi,R8,VGA,5,"5,2",10,Auto(AM-S7),13,...,7750.0,663,450,567,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,Volkswagen Group of,Audi,R8 2WD,VGA,7,"5,2",10,Auto(AM-S7),14,...,6750.0,645,386,528,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,2021,Toyota,TOYOTA,LAND CRUISER WAGON 4WD,TYX,6,"5,7",8,Auto(S8),13,...,7000.0,698,520,618,NaN,NaN,NaN,NaN,NaN,NaN
1161,2021,Toyota,TOYOTA,SEQUOIA 4WD,TYX,34,"5,7",8,Auto(S6),13,...,7000.0,697,521,618,NaN,NaN,NaN,NaN,NaN,NaN
1162,2021,Volkswagen Group of,Volkswagen,Atlas 4Motion,VGA,1,"3,6",6,Auto(S8),16,...,3750.0,547,409,485,NaN,NaN,NaN,NaN,NaN,NaN
1163,2021,Volvo,"Volvo Cars of North America, LLC",XC90 AWD,VVX,52,2,4,Auto(S8),19,...,3500.0,456,318,394,NaN,NaN,NaN,NaN,NaN,NaN
1164,2021,Volvo,"Volvo Cars of North America, LLC",XC90 AWD,VVX,53,2,4,Auto(S8),20,...,3000.0,433,314,380,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
NSX = FE.copy()
NSX = NSX.fillna("limpieza de datos")
NSX

,Model Year,Mfr Name,Division,Carline,Verify Mfr Cd,Index (Model Type Index),Eng Displ,# Cyl,Transmission,City FE (Guide) - Conventional Fuel,...,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe
0,2021,Honda,Acura,NSX,HNX,39,"3,5",6,Auto(AM-S9),21,...,4000.0,420,406,420,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos
1,2021,aston martin,Aston Martin Lagonda Ltd,Vantage Manual,ASX,5,4,8,Manual(M7),14,...,6750.0,636,426,541,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos
2,2021,aston martin,Aston Martin Lagonda Ltd,Vantage V8,ASX,4,4,8,Auto(S8),18,...,4750.0,494,364,435,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos
3,2021,Volkswagen Group of,Audi,R8,VGA,5,"5,2",10,Auto(AM-S7),13,...,7750.0,663,450,567,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos
4,2021,Volkswagen Group of,Audi,R8 2WD,VGA,7,"5,2",10,Auto(AM-S7),14,...,6750.0,645,386,528,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,2021,Toyota,TOYOTA,LAND CRUISER WAGON 4WD,TYX,6,"5,7",8,Auto(S8),13,...,7000.0,698,520,618,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos
1161,2021,Toyota,TOYOTA,SEQUOIA 4WD,TYX,34,"5,7",8,Auto(S6),13,...,7000.0,697,521,618,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos
1162,2021,Volkswagen Group of,Volkswagen,Atlas 4Motion,VGA,1,"3,6",6,Auto(S8),16,...,3750.0,547,409,485,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos
1163,2021,Volvo,"Volvo Cars of North America, LLC",XC90 AWD,VVX,52,2,4,Auto(S8),19,...,3500.0,456,318,394,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos
1164,2021,Volvo,"Volvo Cars of North America, LLC",XC90 AWD,VVX,53,2,4,Auto(S8),20,...,3000.0,433,314,380,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos,limpieza de datos

In [67]:
NSX = FE.copy()
NSX[NSX["Division"].isnull()]

Empty DataFrame
Columns: [Model Year, Mfr Name, Division, Carline, Verify Mfr Cd, Index (Model Type Index), Eng Displ, # Cyl, Transmission, City FE (Guide) - Conventional Fuel, Hwy FE (Guide) - Conventional Fuel, Comb FE (Guide) - Conventional Fuel, City Unadj FE - Conventional Fuel, Hwy Unadj FE - Conventional Fuel, Comb Unadj FE - Conventional Fuel, City Unrd Adj FE - Conventional Fuel, Hwy Unrd Adj FE - Conventional Fuel, Comb Unrd Adj FE - Conventional Fuel, Guzzler? , Air Aspir Method, Air Aspiration Method Desc, Trans, Trans Desc, Trans, Other, # Gears, Lockup Torque Converter, Trans Creeper Gear, Drive Sys, Drive Desc, Max Ethanol % - Gasoline, Max Biodiesel %, Range1 - Model Ty, Fuel Usage  - Conventional Fuel, Fuel Usage Desc - Conventional Fuel, Fuel Unit - Conventional Fuel, Fuel Unit Desc - Conventional Fuel, Gas Guzzler Exempt, Gas Guzzler Exempt Desc, 2Dr Pass Vol, 2Dr Lugg Vol, 4Dr Pass Vol, 4Dr Lugg Vol, Htchbk Pass Vol, Htchbk Lugg Vol, Annual Fuel1 Cost, EPA Calculated, City2 FE (Guide) - Alternative Fuel, Hwy2 Fuel FE (Guide) - Alternative Fuel, Comb2 Fuel FE (Guide) - Alternative Fuel, City2 Unadj FE - Alternative Fuel, Hwy2 Unadj FE - Alternative Fuel, Comb2 Unadj FE - Alternative Fuel, City2 Unrd Adj FE - Alternative Fuel, Hwy2 Unrd Adj FE - Alternative Fuel, Cmb2 Unrd Adj FE - Alternative Fuel,  Range2 - Alt Fuel Model Typ Driving Range - Alternative Fuel,  Fuel2 Usage - Alternative Fuel,  Fuel2 Usage Desc - Alternative Fuel, Fuel2 Unit - Alternative Fuel, Fuel2 Unit Desc - Alternative Fuel, Fuel2 Annual Fuel Cost - Alternative Fuel, City CO2 Rounded Adjusted - Fuel2, Hwy CO2 Rounded Adjusted - Fuel2, Comb CO2 Rounded Adjusted - Fuel2, Fuel2 EPA , Descriptor - Model Type (40 Char or less), Intake Valves Per Cyl, Exhaust Valves Per Cyl, Carline Class, Carline Class Desc, Car/Truck Category - Cash for Clunkers Bill., Calc Approach Desc, Release Date, EPA FE Label Dataset ID, Unnamed: 74, Unique Label?, Label Recalc?, Relabel, Relabel Desc, Suppressed?, Police/Emerg?, Comments - Mfr Eng Cnfg, Cyl Deact?, Cyl Deact Desc, Var Valve Timing?, Var Valve Timing Desc, Var Valve Lift?, Var Valve Lift Desc, Energy Storage Device Desc, Energy Storage Device,If Other, # Batteries, Battery Type Desc, Battery Type, If Other, Total Voltage for Battery Pack(s), Batt Energy Capacity (Amp-hrs), Batt Specific Energy (Watt-hr/kg), Batt Charger Type Desc, Comments, # Capacitors, Regen Braking Type Desc, ...]
Index: []

[0 rows x 155 columns]

In [68]:
NSX = FE.copy()
NSX[NSX["Division"].notnull()]

,Model Year,Mfr Name,Division,Carline,Verify Mfr Cd,Index (Model Type Index),Eng Displ,# Cyl,Transmission,City FE (Guide) - Conventional Fuel,...,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe
0,2021,Honda,Acura,NSX,HNX,39,"3,5",6,Auto(AM-S9),21,...,4000.0,420,406,420,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,aston martin,Aston Martin Lagonda Ltd,Vantage Manual,ASX,5,4,8,Manual(M7),14,...,6750.0,636,426,541,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,aston martin,Aston Martin Lagonda Ltd,Vantage V8,ASX,4,4,8,Auto(S8),18,...,4750.0,494,364,435,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,Volkswagen Group of,Audi,R8,VGA,5,"5,2",10,Auto(AM-S7),13,...,7750.0,663,450,567,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,Volkswagen Group of,Audi,R8 2WD,VGA,7,"5,2",10,Auto(AM-S7),14,...,6750.0,645,386,528,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,2021,Toyota,TOYOTA,LAND CRUISER WAGON 4WD,TYX,6,"5,7",8,Auto(S8),13,...,7000.0,698,520,618,NaN,NaN,NaN,NaN,NaN,NaN
1161,2021,Toyota,TOYOTA,SEQUOIA 4WD,TYX,34,"5,7",8,Auto(S6),13,...,7000.0,697,521,618,NaN,NaN,NaN,NaN,NaN,NaN
1162,2021,Volkswagen Group of,Volkswagen,Atlas 4Motion,VGA,1,"3,6",6,Auto(S8),16,...,3750.0,547,409,485,NaN,NaN,NaN,NaN,NaN,NaN
1163,2021,Volvo,"Volvo Cars of North America, LLC",XC90 AWD,VVX,52,2,4,Auto(S8),19,...,3500.0,456,318,394,NaN,NaN,NaN,NaN,NaN,NaN
1164,2021,Volvo,"Volvo Cars of North America, LLC",XC90 AWD,VVX,53,2,4,Auto(S8),20,...,3000.0,433,314,380,NaN,NaN,NaN,NaN,NaN,NaN

In [1]:
ruta = "C:\\Users\\WIN10\\Desktop\\DS_TOTAL\\FE Guide_1.csv"

In [2]:
import pandas as pd

In [5]:
GUIA = pd.read_csv(ruta, sep = ";")
GUIA.head(5)

,Model Year,Mfr Name,Division,Carline,Verify Mfr Cd,Index (Model Type Index),Eng Displ,# Cyl,Transmission,City FE (Guide) - Conventional Fuel,...,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe
0,2021,Honda,Acura,NSX,HNX,39,"3,5",6,Auto(AM-S9),21,...,4000.0,420,406,420,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,aston martin,Aston Martin Lagonda Ltd,Vantage Manual,ASX,5,4,8,Manual(M7),14,...,6750.0,636,426,541,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,aston martin,Aston Martin Lagonda Ltd,Vantage V8,ASX,4,4,8,Auto(S8),18,...,4750.0,494,364,435,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,Volkswagen Group of,Audi,R8,VGA,5,"5,2",10,Auto(AM-S7),13,...,7750.0,663,450,567,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,Volkswagen Group of,Audi,R8 2WD,VGA,7,"5,2",10,Auto(AM-S7),14,...,6750.0,645,386,528,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
MODEL = GUIA.copy()
MODEL["TYP_CONV"] = MODEL["Index (Model Type Index)"] + MODEL["City FE (Guide) - Conventional Fuel"].copy()
MODEL.head(3)

,Model Year,Mfr Name,Division,Carline,Verify Mfr Cd,Index (Model Type Index),Eng Displ,# Cyl,Transmission,City FE (Guide) - Conventional Fuel,...,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe,TYP_CONV
0,2021,Honda,Acura,NSX,HNX,39,"3,5",6,Auto(AM-S9),21,...,420,406,420,NaN,NaN,NaN,NaN,NaN,NaN,60
1,2021,aston martin,Aston Martin Lagonda Ltd,Vantage Manual,ASX,5,4,8,Manual(M7),14,...,636,426,541,NaN,NaN,NaN,NaN,NaN,NaN,19
2,2021,aston martin,Aston Martin Lagonda Ltd,Vantage V8,ASX,4,4,8,Auto(S8),18,...,494,364,435,NaN,NaN,NaN,NaN,NaN,NaN,22

In [9]:
MODEL.iloc[:,140:]

,#2 EPA Smog Rating,SmartWay2 (EPA-deriv,#3 Smog Rating Test Group,#3 Mfr Smog Rating (,#4 Smog Rating Test Group,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe,TYP_CONV
0,NaN,NaN,NaN,NaN,NaN,4000.0,420,406,420,NaN,NaN,NaN,NaN,NaN,NaN,60
1,NaN,NaN,NaN,NaN,NaN,6750.0,636,426,541,NaN,NaN,NaN,NaN,NaN,NaN,19
2,NaN,NaN,NaN,NaN,NaN,4750.0,494,364,435,NaN,NaN,NaN,NaN,NaN,NaN,22
3,NaN,NaN,NaN,NaN,NaN,7750.0,663,450,567,NaN,NaN,NaN,NaN,NaN,NaN,18
4,NaN,NaN,NaN,NaN,NaN,6750.0,645,386,528,NaN,NaN,NaN,NaN,NaN,NaN,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,NaN,NaN,NaN,NaN,NaN,7000.0,698,520,618,NaN,NaN,NaN,NaN,NaN,NaN,19
1161,NaN,NaN,NaN,NaN,NaN,7000.0,697,521,618,NaN,NaN,NaN,NaN,NaN,NaN,47
1162,NaN,NaN,NaN,NaN,NaN,3750.0,547,409,485,NaN,NaN,NaN,NaN,NaN,NaN,17
1163,NaN,NaN,NaN,NaN,NaN,3500.0,456,318,394,NaN,NaN,NaN,NaN,NaN,NaN,71
1164,NaN,NaN,NaN,NaN,NaN,3000.0,433,314,380,NaN,NaN,NaN,NaN,NaN,NaN,73

In [26]:
COL_VACIA = MODEL.iloc[:,140:]
COL_VACIA

,#2 EPA Smog Rating,SmartWay2 (EPA-deriv,#3 Smog Rating Test Group,#3 Mfr Smog Rating (,#4 Smog Rating Test Group,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe,TYP_CONV
0,NaN,NaN,NaN,NaN,NaN,4000.0,420,406,420,NaN,NaN,NaN,NaN,NaN,NaN,60
1,NaN,NaN,NaN,NaN,NaN,6750.0,636,426,541,NaN,NaN,NaN,NaN,NaN,NaN,19
2,NaN,NaN,NaN,NaN,NaN,4750.0,494,364,435,NaN,NaN,NaN,NaN,NaN,NaN,22
3,NaN,NaN,NaN,NaN,NaN,7750.0,663,450,567,NaN,NaN,NaN,NaN,NaN,NaN,18
4,NaN,NaN,NaN,NaN,NaN,6750.0,645,386,528,NaN,NaN,NaN,NaN,NaN,NaN,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,NaN,NaN,NaN,NaN,NaN,7000.0,698,520,618,NaN,NaN,NaN,NaN,NaN,NaN,19
1161,NaN,NaN,NaN,NaN,NaN,7000.0,697,521,618,NaN,NaN,NaN,NaN,NaN,NaN,47
1162,NaN,NaN,NaN,NaN,NaN,3750.0,547,409,485,NaN,NaN,NaN,NaN,NaN,NaN,17
1163,NaN,NaN,NaN,NaN,NaN,3500.0,456,318,394,NaN,NaN,NaN,NaN,NaN,NaN,71
1164,NaN,NaN,NaN,NaN,NaN,3000.0,433,314,380,NaN,NaN,NaN,NaN,NaN,NaN,73

In [28]:
COL_NUEVA = COL_VACIA.copy()
COL_NUEVA.head(3)

,#2 EPA Smog Rating,SmartWay2 (EPA-deriv,#3 Smog Rating Test Group,#3 Mfr Smog Rating (,#4 Smog Rating Test Group,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe,TYP_CONV
0,NaN,NaN,NaN,NaN,NaN,4000.0,420,406,420,NaN,NaN,NaN,NaN,NaN,NaN,60
1,NaN,NaN,NaN,NaN,NaN,6750.0,636,426,541,NaN,NaN,NaN,NaN,NaN,NaN,19
2,NaN,NaN,NaN,NaN,NaN,4750.0,494,364,435,NaN,NaN,NaN,NaN,NaN,NaN,22

In [33]:
COL_NUEVA = COL_VACIA.copy()
COL_NUEVA

,#2 EPA Smog Rating,SmartWay2 (EPA-deriv,#3 Smog Rating Test Group,#3 Mfr Smog Rating (,#4 Smog Rating Test Group,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe,TYP_CONV
0,NaN,NaN,NaN,NaN,NaN,4000.0,420,406,420,NaN,NaN,NaN,NaN,NaN,NaN,60
1,NaN,NaN,NaN,NaN,NaN,6750.0,636,426,541,NaN,NaN,NaN,NaN,NaN,NaN,19
2,NaN,NaN,NaN,NaN,NaN,4750.0,494,364,435,NaN,NaN,NaN,NaN,NaN,NaN,22
3,NaN,NaN,NaN,NaN,NaN,7750.0,663,450,567,NaN,NaN,NaN,NaN,NaN,NaN,18
4,NaN,NaN,NaN,NaN,NaN,6750.0,645,386,528,NaN,NaN,NaN,NaN,NaN,NaN,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,NaN,NaN,NaN,NaN,NaN,7000.0,698,520,618,NaN,NaN,NaN,NaN,NaN,NaN,19
1161,NaN,NaN,NaN,NaN,NaN,7000.0,697,521,618,NaN,NaN,NaN,NaN,NaN,NaN,47
1162,NaN,NaN,NaN,NaN,NaN,3750.0,547,409,485,NaN,NaN,NaN,NaN,NaN,NaN,17
1163,NaN,NaN,NaN,NaN,NaN,3500.0,456,318,394,NaN,NaN,NaN,NaN,NaN,NaN,71
1164,NaN,NaN,NaN,NaN,NaN,3000.0,433,314,380,NaN,NaN,NaN,NaN,NaN,NaN,73

In [35]:
COL_NUEVA = COL_VACIA.copy()

COL_NUEVA["SmartWay2 (EPA-deriv"] = COL_NUEVA["SmartWay2 (EPA-deriv"].fillna(6).copy()
COL_NUEVA["#3 Smog Rating Test Group"] = COL_NUEVA["#3 Smog Rating Test Group"].fillna(158).copy()
COL_NUEVA["#4 Smog Rating Test Group"] = COL_NUEVA["#4 Smog Rating Test Group"].fillna(87).copy()
COL_NUEVA["CO2-PHEV Composit"] = COL_NUEVA["CO2-PHEV Composit"].fillna(31).copy()
COL_NUEVA["240V Charge Ti"] = COL_NUEVA["240V Charge Ti"].fillna(91).copy()

COL_NUEVA.head(6)

,#2 EPA Smog Rating,SmartWay2 (EPA-deriv,#3 Smog Rating Test Group,#3 Mfr Smog Rating (,#4 Smog Rating Test Group,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe,TYP_CONV
0,NaN,6.0,158.0,NaN,87.0,4000.0,420,406,420,31.0,91.0,NaN,NaN,NaN,NaN,60
1,NaN,6.0,158.0,NaN,87.0,6750.0,636,426,541,31.0,91.0,NaN,NaN,NaN,NaN,19
2,NaN,6.0,158.0,NaN,87.0,4750.0,494,364,435,31.0,91.0,NaN,NaN,NaN,NaN,22
3,NaN,6.0,158.0,NaN,87.0,7750.0,663,450,567,31.0,91.0,NaN,NaN,NaN,NaN,18
4,NaN,6.0,158.0,NaN,87.0,6750.0,645,386,528,31.0,91.0,NaN,NaN,NaN,NaN,21
5,NaN,6.0,158.0,NaN,87.0,7750.0,663,450,567,31.0,91.0,NaN,NaN,NaN,NaN,19

In [46]:
COL_NUEVA = COL_VACIA.copy()
COL_NUEVA["#3 Smog Rating Test Group"] = COL_NUEVA["#3 Smog Rating Test Group"].fillna(5)
COL_NUEVA["#4 Smog Rating Test Group"] = COL_NUEVA["#4 Smog Rating Test Group"].fillna(7)
COL_NUEVA["CO2-PHEV Composit"] = COL_NUEVA["CO2-PHEV Composit"].fillna(8)

COL_NUEVA

,#2 EPA Smog Rating,SmartWay2 (EPA-deriv,#3 Smog Rating Test Group,#3 Mfr Smog Rating (,#4 Smog Rating Test Group,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe,TYP_CONV
0,NaN,NaN,5.0,NaN,7.0,4000.0,420,406,420,8.0,NaN,NaN,NaN,NaN,NaN,60
1,NaN,NaN,5.0,NaN,7.0,6750.0,636,426,541,8.0,NaN,NaN,NaN,NaN,NaN,19
2,NaN,NaN,5.0,NaN,7.0,4750.0,494,364,435,8.0,NaN,NaN,NaN,NaN,NaN,22
3,NaN,NaN,5.0,NaN,7.0,7750.0,663,450,567,8.0,NaN,NaN,NaN,NaN,NaN,18
4,NaN,NaN,5.0,NaN,7.0,6750.0,645,386,528,8.0,NaN,NaN,NaN,NaN,NaN,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,NaN,NaN,5.0,NaN,7.0,7000.0,698,520,618,8.0,NaN,NaN,NaN,NaN,NaN,19
1161,NaN,NaN,5.0,NaN,7.0,7000.0,697,521,618,8.0,NaN,NaN,NaN,NaN,NaN,47
1162,NaN,NaN,5.0,NaN,7.0,3750.0,547,409,485,8.0,NaN,NaN,NaN,NaN,NaN,17
1163,NaN,NaN,5.0,NaN,7.0,3500.0,456,318,394,8.0,NaN,NaN,NaN,NaN,NaN,71
1164,NaN,NaN,5.0,NaN,7.0,3000.0,433,314,380,8.0,NaN,NaN,NaN,NaN,NaN,73

In [55]:
COL_NUEVA = COL_VACIA.copy()

COL_NUEVA["Comb CO2 Rouno"] = COL_NUEVA["Comb CO2 Roun"].fillna(COL_NUEVA["Comb CO2 Roun"].sum())
                                                                       

COL_NUEVA

,#2 EPA Smog Rating,SmartWay2 (EPA-deriv,#3 Smog Rating Test Group,#3 Mfr Smog Rating (,#4 Smog Rating Test Group,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe,TYP_CONV,Comb CO2 Rouno
0,NaN,NaN,NaN,NaN,NaN,4000.0,420,406,420,0.0,NaN,NaN,NaN,NaN,NaN,60,420
1,NaN,NaN,NaN,NaN,NaN,6750.0,636,426,541,0.0,NaN,NaN,NaN,NaN,NaN,19,541
2,NaN,NaN,NaN,NaN,NaN,4750.0,494,364,435,0.0,NaN,NaN,NaN,NaN,NaN,22,435
3,NaN,NaN,NaN,NaN,NaN,7750.0,663,450,567,0.0,NaN,NaN,NaN,NaN,NaN,18,567
4,NaN,NaN,NaN,NaN,NaN,6750.0,645,386,528,0.0,NaN,NaN,NaN,NaN,NaN,21,528
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,NaN,NaN,NaN,NaN,NaN,7000.0,698,520,618,0.0,NaN,NaN,NaN,NaN,NaN,19,618
1161,NaN,NaN,NaN,NaN,NaN,7000.0,697,521,618,0.0,NaN,NaN,NaN,NaN,NaN,47,618
1162,NaN,NaN,NaN,NaN,NaN,3750.0,547,409,485,0.0,NaN,NaN,NaN,NaN,NaN,17,485
1163,NaN,NaN,NaN,NaN,NaN,3500.0,456,318,394,0.0,NaN,NaN,NaN,NaN,NaN,71,394
1164,NaN,NaN,NaN,NaN,NaN,3000.0,433,314,380,0.0,NaN,NaN,NaN,NaN,NaN,73,380

In [58]:
COL_NUEVA.fillna("-")

,#2 EPA Smog Rating,SmartWay2 (EPA-deriv,#3 Smog Rating Test Group,#3 Mfr Smog Rating (,#4 Smog Rating Test Group,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe,TYP_CONV,Comb CO2 Rouno
0,-,-,-,-,-,4000.0,420,406,420,0.0,-,-,-,-,-,60,420
1,-,-,-,-,-,6750.0,636,426,541,0.0,-,-,-,-,-,19,541
2,-,-,-,-,-,4750.0,494,364,435,0.0,-,-,-,-,-,22,435
3,-,-,-,-,-,7750.0,663,450,567,0.0,-,-,-,-,-,18,567
4,-,-,-,-,-,6750.0,645,386,528,0.0,-,-,-,-,-,21,528
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,-,-,-,-,-,7000.0,698,520,618,0.0,-,-,-,-,-,19,618
1161,-,-,-,-,-,7000.0,697,521,618,0.0,-,-,-,-,-,47,618
1162,-,-,-,-,-,3750.0,547,409,485,0.0,-,-,-,-,-,17,485
1163,-,-,-,-,-,3500.0,456,318,394,0.0,-,-,-,-,-,71,394
1164,-,-,-,-,-,3000.0,433,314,380,0.0,-,-,-,-,-,73,380

In [72]:
COL_NUEVA = COL_VACIA.copy()
COL_NUEVA["SmartWay2 (EPA-deriv"] = COL_NUEVA["SmartWay2 (EPA-deriv"].fillna("-")
COL_NUEVA["240V Charge Ti"] = COL_NUEVA["240V Charge Ti"].fillna(5)
COL_NUEVA["City PHEV Composite MPGe"] = COL_NUEVA["City PHEV Composite MPGe"].fillna("sin datos")
COL_NUEVA["CO2-PHEV Composit"] = COL_NUEVA["CO2-PHEV Composit"].fillna(COL_NUEVA["CO2-PHEV Composit"]
                                                                        .sum())

COL_NUEVA

,#2 EPA Smog Rating,SmartWay2 (EPA-deriv,#3 Smog Rating Test Group,#3 Mfr Smog Rating (,#4 Smog Rating Test Group,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe,TYP_CONV
0,NaN,-,NaN,NaN,NaN,4000.0,420,406,420,0.0,5.0,NaN,sin datos,NaN,NaN,60
1,NaN,-,NaN,NaN,NaN,6750.0,636,426,541,0.0,5.0,NaN,sin datos,NaN,NaN,19
2,NaN,-,NaN,NaN,NaN,4750.0,494,364,435,0.0,5.0,NaN,sin datos,NaN,NaN,22
3,NaN,-,NaN,NaN,NaN,7750.0,663,450,567,0.0,5.0,NaN,sin datos,NaN,NaN,18
4,NaN,-,NaN,NaN,NaN,6750.0,645,386,528,0.0,5.0,NaN,sin datos,NaN,NaN,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,NaN,-,NaN,NaN,NaN,7000.0,698,520,618,0.0,5.0,NaN,sin datos,NaN,NaN,19
1161,NaN,-,NaN,NaN,NaN,7000.0,697,521,618,0.0,5.0,NaN,sin datos,NaN,NaN,47
1162,NaN,-,NaN,NaN,NaN,3750.0,547,409,485,0.0,5.0,NaN,sin datos,NaN,NaN,17
1163,NaN,-,NaN,NaN,NaN,3500.0,456,318,394,0.0,5.0,NaN,sin datos,NaN,NaN,71
1164,NaN,-,NaN,NaN,NaN,3000.0,433,314,380,0.0,5.0,NaN,sin datos,NaN,NaN,73

In [78]:
LISTA = list(range(COL_NUEVA.shape[0]))
COL_NUEVA["RANGO"] = LISTA
COL_NUEVA

,#2 EPA Smog Rating,SmartWay2 (EPA-deriv,#3 Smog Rating Test Group,#3 Mfr Smog Rating (,#4 Smog Rating Test Group,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe,TYP_CONV,RANGO
0,NaN,-,NaN,NaN,NaN,4000.0,420,406,420,0.0,5.0,NaN,sin datos,NaN,NaN,60,0
1,NaN,-,NaN,NaN,NaN,6750.0,636,426,541,0.0,5.0,NaN,sin datos,NaN,NaN,19,1
2,NaN,-,NaN,NaN,NaN,4750.0,494,364,435,0.0,5.0,NaN,sin datos,NaN,NaN,22,2
3,NaN,-,NaN,NaN,NaN,7750.0,663,450,567,0.0,5.0,NaN,sin datos,NaN,NaN,18,3
4,NaN,-,NaN,NaN,NaN,6750.0,645,386,528,0.0,5.0,NaN,sin datos,NaN,NaN,21,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,NaN,-,NaN,NaN,NaN,7000.0,698,520,618,0.0,5.0,NaN,sin datos,NaN,NaN,19,1160
1161,NaN,-,NaN,NaN,NaN,7000.0,697,521,618,0.0,5.0,NaN,sin datos,NaN,NaN,47,1161
1162,NaN,-,NaN,NaN,NaN,3750.0,547,409,485,0.0,5.0,NaN,sin datos,NaN,NaN,17,1162
1163,NaN,-,NaN,NaN,NaN,3500.0,456,318,394,0.0,5.0,NaN,sin datos,NaN,NaN,71,1163
1164,NaN,-,NaN,NaN,NaN,3000.0,433,314,380,0.0,5.0,NaN,sin datos,NaN,NaN,73,1164

In [80]:
AGREGANDO_COL = list(range(COL_NUEVA.shape[0]))
COL_NUEVA["COLUMNA_1"] = AGREGANDO_COL
COL_NUEVA

,#2 EPA Smog Rating,SmartWay2 (EPA-deriv,#3 Smog Rating Test Group,#3 Mfr Smog Rating (,#4 Smog Rating Test Group,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe,TYP_CONV,RANGO,COLUMNA_1
0,NaN,-,NaN,NaN,NaN,4000.0,420,406,420,0.0,5.0,NaN,sin datos,NaN,NaN,60,0,0
1,NaN,-,NaN,NaN,NaN,6750.0,636,426,541,0.0,5.0,NaN,sin datos,NaN,NaN,19,1,1
2,NaN,-,NaN,NaN,NaN,4750.0,494,364,435,0.0,5.0,NaN,sin datos,NaN,NaN,22,2,2
3,NaN,-,NaN,NaN,NaN,7750.0,663,450,567,0.0,5.0,NaN,sin datos,NaN,NaN,18,3,3
4,NaN,-,NaN,NaN,NaN,6750.0,645,386,528,0.0,5.0,NaN,sin datos,NaN,NaN,21,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,NaN,-,NaN,NaN,NaN,7000.0,698,520,618,0.0,5.0,NaN,sin datos,NaN,NaN,19,1160,1160
1161,NaN,-,NaN,NaN,NaN,7000.0,697,521,618,0.0,5.0,NaN,sin datos,NaN,NaN,47,1161,1161
1162,NaN,-,NaN,NaN,NaN,3750.0,547,409,485,0.0,5.0,NaN,sin datos,NaN,NaN,17,1162,1162
1163,NaN,-,NaN,NaN,NaN,3500.0,456,318,394,0.0,5.0,NaN,sin datos,NaN,NaN,71,1163,1163
1164,NaN,-,NaN,NaN,NaN,3000.0,433,314,380,0.0,5.0,NaN,sin datos,NaN,NaN,73,1164,1164

In [85]:
INSERTANDO_COL = list(range(COL_NUEVA.shape[0]))
COL_NUEVA["COL_2"] = INSERTANDO_COL
COL_NUEVA

,#2 EPA Smog Rating,SmartWay2 (EPA-deriv,#3 Smog Rating Test Group,#3 Mfr Smog Rating (,#4 Smog Rating Test Group,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe,TYP_CONV,RANGO,COLUMNA_1,COL_2
0,NaN,-,NaN,NaN,NaN,4000.0,420,406,420,0.0,5.0,NaN,sin datos,NaN,NaN,60,0,0,0
1,NaN,-,NaN,NaN,NaN,6750.0,636,426,541,0.0,5.0,NaN,sin datos,NaN,NaN,19,1,1,1
2,NaN,-,NaN,NaN,NaN,4750.0,494,364,435,0.0,5.0,NaN,sin datos,NaN,NaN,22,2,2,2
3,NaN,-,NaN,NaN,NaN,7750.0,663,450,567,0.0,5.0,NaN,sin datos,NaN,NaN,18,3,3,3
4,NaN,-,NaN,NaN,NaN,6750.0,645,386,528,0.0,5.0,NaN,sin datos,NaN,NaN,21,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,NaN,-,NaN,NaN,NaN,7000.0,698,520,618,0.0,5.0,NaN,sin datos,NaN,NaN,19,1160,1160,1160
1161,NaN,-,NaN,NaN,NaN,7000.0,697,521,618,0.0,5.0,NaN,sin datos,NaN,NaN,47,1161,1161,1161
1162,NaN,-,NaN,NaN,NaN,3750.0,547,409,485,0.0,5.0,NaN,sin datos,NaN,NaN,17,1162,1162,1162
1163,NaN,-,NaN,NaN,NaN,3500.0,456,318,394,0.0,5.0,NaN,sin datos,NaN,NaN,71,1163,1163,1163
1164,NaN,-,NaN,NaN,NaN,3000.0,433,314,380,0.0,5.0,NaN,sin datos,NaN,NaN,73,1164,1164,1164

In [87]:
COL_3 = list(range(COL_NUEVA.shape[0]))
COL_NUEVA["COL_3"] = COL_3
COL_NUEVA

,#2 EPA Smog Rating,SmartWay2 (EPA-deriv,#3 Smog Rating Test Group,#3 Mfr Smog Rating (,#4 Smog Rating Test Group,$ You Spend o,City CO2 Rounded Adjusted,Hwy CO2 Rounded Adjusted,Comb CO2 Roun,CO2-PHEV Composit,240V Charge Ti,120V Charge time at 120 Volts (hours),City PHEV Composite MPGe,Hwy PHEV Composite MPGe,Comb PHEV Composite MPGe,TYP_CONV,RANGO,COLUMNA_1,COL_2,COL_3
0,NaN,-,NaN,NaN,NaN,4000.0,420,406,420,0.0,5.0,NaN,sin datos,NaN,NaN,60,0,0,0,0
1,NaN,-,NaN,NaN,NaN,6750.0,636,426,541,0.0,5.0,NaN,sin datos,NaN,NaN,19,1,1,1,1
2,NaN,-,NaN,NaN,NaN,4750.0,494,364,435,0.0,5.0,NaN,sin datos,NaN,NaN,22,2,2,2,2
3,NaN,-,NaN,NaN,NaN,7750.0,663,450,567,0.0,5.0,NaN,sin datos,NaN,NaN,18,3,3,3,3
4,NaN,-,NaN,NaN,NaN,6750.0,645,386,528,0.0,5.0,NaN,sin datos,NaN,NaN,21,4,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,NaN,-,NaN,NaN,NaN,7000.0,698,520,618,0.0,5.0,NaN,sin datos,NaN,NaN,19,1160,1160,1160,1160
1161,NaN,-,NaN,NaN,NaN,7000.0,697,521,618,0.0,5.0,NaN,sin datos,NaN,NaN,47,1161,1161,1161,1161
1162,NaN,-,NaN,NaN,NaN,3750.0,547,409,485,0.0,5.0,NaN,sin datos,NaN,NaN,17,1162,1162,1162,1162
1163,NaN,-,NaN,NaN,NaN,3500.0,456,318,394,0.0,5.0,NaN,sin datos,NaN,NaN,71,1163,1163,1163,1163
1164,NaN,-,NaN,NaN,NaN,3000.0,433,314,380,0.0,5.0,NaN,sin datos,NaN,NaN,73,1164,1164,1164,1164

In [93]:
COL_NUEVA.loc[[1,11,100,500,900,987,1160],["City CO2 Rounded Adjusted","240V Charge Ti"]]

      City CO2 Rounded Adjusted  240V Charge Ti
1                           636             5.0
11                         1055             5.0
100                         432             5.0
500                         334             5.0
900                         481             5.0
987                         416             5.0
1160                        698             5.0

In [96]:
COL_NUEVA.loc[[200,300,700,900,1001,100],['SmartWay2 (EPA-deriv',
       '#3 Smog Rating Test Group', '#3 Mfr Smog Rating (',
       '#4 Smog Rating Test Group']]

,SmartWay2 (EPA-deriv,#3 Smog Rating Test Group,#3 Mfr Smog Rating (,#4 Smog Rating Test Group
200,-,NaN,NaN,NaN
300,-,NaN,NaN,NaN
700,-,NaN,NaN,NaN
900,-,NaN,NaN,NaN
1001,-,NaN,NaN,NaN
100,-,NaN,NaN,NaN

In [97]:
AGREGAR_FILA =   COL_NUEVA.loc[[200,300,700,900,1001,100],['SmartWay2 (EPA-deriv',
       '#3 Smog Rating Test Group', '#3 Mfr Smog Rating (',
       '#4 Smog Rating Test Group']].copy()

AGREGAR_FILA

,SmartWay2 (EPA-deriv,#3 Smog Rating Test Group,#3 Mfr Smog Rating (,#4 Smog Rating Test Group
200,-,NaN,NaN,NaN
300,-,NaN,NaN,NaN
700,-,NaN,NaN,NaN
900,-,NaN,NaN,NaN
1001,-,NaN,NaN,NaN
100,-,NaN,NaN,NaN

In [112]:
AGREGANDO_FILA = AGREGAR_FILA.append( {
    "SmartWay2 (EPA-deriv" : 3000,
    "#3 Smog Rating Test Group" : "TRABAJANDO",
    "#3 Mfr Smog Rating (" : "SIN DATOS" ,
    "#4 Smog Rating Test Group" : "TRABAJANDO" },ignore_index=True ).copy()
    
AGREGANDO_FILA

,SmartWay2 (EPA-deriv,#3 Smog Rating Test Group,#3 Mfr Smog Rating (,#4 Smog Rating Test Group
0,-,NaN,NaN,NaN
1,-,NaN,NaN,NaN
2,-,NaN,NaN,NaN
3,-,NaN,NaN,NaN
4,-,NaN,NaN,NaN
5,-,NaN,NaN,NaN
6,3000,TRABAJANDO,SIN DATOS,TRABAJANDO

In [113]:
AGREGANDO_FILA

,SmartWay2 (EPA-deriv,#3 Smog Rating Test Group,#3 Mfr Smog Rating (,#4 Smog Rating Test Group
0,-,NaN,NaN,NaN
1,-,NaN,NaN,NaN
2,-,NaN,NaN,NaN
3,-,NaN,NaN,NaN
4,-,NaN,NaN,NaN
5,-,NaN,NaN,NaN
6,3000,TRABAJANDO,SIN DATOS,TRABAJANDO

In [114]:
AGREGANDO_FILA = AGREGAR_FILA.copy()
AGREGANDO_FILA

,SmartWay2 (EPA-deriv,#3 Smog Rating Test Group,#3 Mfr Smog Rating (,#4 Smog Rating Test Group
200,-,NaN,NaN,NaN
300,-,NaN,NaN,NaN
700,-,NaN,NaN,NaN
900,-,NaN,NaN,NaN
1001,-,NaN,NaN,NaN
100,-,NaN,NaN,NaN

In [117]:
AGREGANDO_FILA = AGREGAR_FILA.copy()
AGREGANDO_FILA = AGREGAR_FILA.append(
    { "SmartWay2 (EPA-deriv" : 200,
      "#3 Smog Rating Test Group": 60,
      "#3 Mfr Smog Rating (": 90,
      "#4 Smog Rating Test Group":50
        
        
    },ignore_index = True)

AGREGANDO_FILA

,SmartWay2 (EPA-deriv,#3 Smog Rating Test Group,#3 Mfr Smog Rating (,#4 Smog Rating Test Group
0,-,NaN,NaN,NaN
1,-,NaN,NaN,NaN
2,-,NaN,NaN,NaN
3,-,NaN,NaN,NaN
4,-,NaN,NaN,NaN
5,-,NaN,NaN,NaN
6,200,60.0,90.0,50.0

In [119]:
AGREGANDO_FILA = AGREGAR_FILA.copy()
AGREGANDO_FILA = AGREGAR_FILA.append(
    { "SmartWay2 (EPA-deriv" : "NO DATOS",
     "#3 Smog Rating Test Group" : "EN PROCESO",
     "#3 Mfr Smog Rating (" : "ACTUALIZANDO",
     "#4 Smog Rating Test Group" : "ERROR" 
    }, ignore_index = True

)

AGREGANDO_FILA

,SmartWay2 (EPA-deriv,#3 Smog Rating Test Group,#3 Mfr Smog Rating (,#4 Smog Rating Test Group
0,-,NaN,NaN,NaN
1,-,NaN,NaN,NaN
2,-,NaN,NaN,NaN
3,-,NaN,NaN,NaN
4,-,NaN,NaN,NaN
5,-,NaN,NaN,NaN
6,NO DATOS,EN PROCESO,ACTUALIZANDO,ERROR